services:
  - type: web
    name: statoku
    env: docker
    plan: free
    region: singapore
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PHP_ENV
        value: production
      - key: APP_NAME
        value: "Learn with Statoku"
